export const state = {
  isTauri: Boolean(window.__TAURI__),
  page: "home",
  connected: false,
  listening: false,
  deviceName: null,
  deviceId: null,
  pairingCode: "",
  pairingIp: null,
  pairingPort: null,
  noteText: "",
  settings: null,
  history: [],
  devices: [],
  activity: [],
  dataFilter: "all",
  recordsSearch: "",
  serviceRunning: false,
  asrConfigured: false,
  localAsrAvailable: true,
  pendingEngine: null,
  asrConfigExpanded: false,
  qwen3BinaryAvailable: false,
  qwen3BinaryDownloading: false,
  qwen3Models: { "0.6b": { downloaded: false }, "1.7b": { downloaded: false } },
  qwen3Downloading: null,
  qwen3DownloadProgress: null,
  qwen3ConfigExpanded: false,
  recordsBatchMode: false,
  selectedHistoryIds: [],
  currentVersion: "",
  updateInfo: null,
  updateChecking: false,
  updateInstalling: false,
  updateProgress: null,
  updateBannerDismissed: false,
};
